[package]
name = "sixtyfps-rendering-backend-mcu"
version = "0.1.5"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Rendering backend for SixtyFPS for use on Microcontrollers"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"

[lib]
path = "lib.rs"

[features]
simulator = ["winit", "glutin", "femtovg", "embedded-graphics-simulator"]
default = ["simulator"]

[dependencies]
sixtyfps-corelib = { version = "=0.1.5", path = "../../corelib" }
const-field-offset = { version = "0.1", path = "../../../helper_crates/const-field-offset" }
rgb = "0.8.27"
imgref = "1.6.1"
vtable = { version = "0.1", path = "../../../helper_crates/vtable" }
by_address = "1.0.4"
euclid = "0.22.1"
pin-weak = "1"
scoped-tls-hkt = "0.1"
smallvec = "1.7"
once_cell = "1.5"
derive_more = "0.99.5"
winit = { version = "0.25", default-features = false, optional = true }
glutin = { version = "0.27", default-features = false, optional = true }
femtovg = { version = "0.2.8", optional = true }
embedded-graphics = "0.7.1"
embedded-graphics-simulator = { version = "0.3.0", optional = true, default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = { version = "0.24.0" }
